@API_HostAddress = http://localhost:5212/api

POST {{API_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "ulatruong37@gmail.com",
  "password": "12345678"
}

###
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0IiwiZW1haWwiOiJ1bGF0cnVvbmczN0BnbWFpbC5jb20iLCJyb2xlIjoiTGVhcm5lciIsIm5iZiI6MTc2NjQ4Mjg1OCwiZXhwIjoxNzY2NTY5MjU4LCJpYXQiOjE3NjY0ODI4NTgsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE1MCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE3MyJ9.m_gn86hTxsllfGJMx_5TT0G_RbWw5t92pkv4ZPef8sI
